### PR TITLE
Enhancement: Issue #1 NPM modules updated

### PR DESCRIPTION
**Pull request by Mahesh419**
The following work is conducted in this PR.
- NPM modules updated
- Checked if the app is working properly
- Npm audit issues fixed

### CODE REVIEW

**Review by ashokdey — APPROVED** [review]

**Comment by ashokdey** [comment]
Hello @Mahesh419, I would recommend running **npm audit**, updating in the issue #1  also.

**Comment by Mahesh419** [comment]
> Hello @Mahesh419, I would recommend running **npm audit**, updating in the issue #1 also.

**Review by ashokdey — APPROVED** [review]

**Comment by ashokdey** [comment]
Thanks @Mahesh419 🍹

**Comment by Mahesh419** [comment]
Happy to help :+1:

**Pull request merged**
